msgunfmt cs/LC_MESSAGES/global.mo -o cs/LC_MESSAGES/global.po
msgunfmt de/LC_MESSAGES/global.mo -o de/LC_MESSAGES/global.po
msgunfmt en/LC_MESSAGES/global.mo -o en/LC_MESSAGES/global.po
msgunfmt es/LC_MESSAGES/global.mo -o es/LC_MESSAGES/global.po
msgunfmt es_mx/LC_MESSAGES/global.mo -o es_mx/LC_MESSAGES/global.po
msgunfmt fr/LC_MESSAGES/global.mo -o fr/LC_MESSAGES/global.po
msgunfmt it/LC_MESSAGES/global.mo -o it/LC_MESSAGES/global.po
msgunfmt ja/LC_MESSAGES/global.mo -o ja/LC_MESSAGES/global.po
msgunfmt ko/LC_MESSAGES/global.mo -o ko/LC_MESSAGES/global.po
msgunfmt nl/LC_MESSAGES/global.mo -o nl/LC_MESSAGES/global.po
msgunfmt pl/LC_MESSAGES/global.mo -o pl/LC_MESSAGES/global.po
msgunfmt pt/LC_MESSAGES/global.mo -o pt/LC_MESSAGES/global.po
msgunfmt pt_br/LC_MESSAGES/global.mo -o pt_br/LC_MESSAGES/global.po
msgunfmt ru/LC_MESSAGES/global.mo -o ru/LC_MESSAGES/global.po
msgunfmt th/LC_MESSAGES/global.mo -o th/LC_MESSAGES/global.po
msgunfmt tr/LC_MESSAGES/global.mo -o tr/LC_MESSAGES/global.po
msgunfmt uk/LC_MESSAGES/global.mo -o uk/LC_MESSAGES/global.po
msgunfmt zh/LC_MESSAGES/global.mo -o zh/LC_MESSAGES/global.po
msgunfmt zh_sg/LC_MESSAGES/global.mo -o zh_sg/LC_MESSAGES/global.po
msgunfmt zh_tw/LC_MESSAGES/global.mo -o zh_tw/LC_MESSAGES/global.po