name: ReBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Before rebuild
      run: |
        sudo apt update
        sudo apt install gettext
        chomod +x ReBuildString.sh

    - name: ReBuild
      run: |
        ./ReBuildString.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
