name: ReBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Before Rebuild
      run: |
        sudo apt update
        sudo apt install gettext
        sudo chmod +x ReBuildString.sh
        sudo chmod +x BuildJson.sh

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      
    - name: ReBuild
      run: |
        ./ReBuildString.sh
        node build cs
        node build de
        node build en
        node build es
        node build es_mx
        node build fr
        node build it
        node build ja
        node build ko
        node build nl
        node build pl
        node build pt
        node build pt_br
        node build ru
        node build th
        node build tr
        node build uk
        node build zh
        node build zh_sg
        node build zh_tw

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
