name: ReBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Before Rebuild
      run: |
        sudo apt update
        sudo apt install gettext
        sudo chmod +x ReBuildString.sh
        sudo chmod +x BuildJSON.sh

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      
    - name: ReBuild
      run: |
        ./ReBuildString.sh
        ./BuildJSON.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
